### ISSUE TITLE
MT4 & IG-API

### ISSUE THREAD

**Issue by maxbrown** [femtotrader/ig-markets-rest-api-python-library#8]
Hi femtotrader,

I've tried to port the python code to MT4 but without success.  I don't want to reinvent the wheel so wondered if there is an easy way to access the IG-API via MT4?

Placing trades via MT4 without the use of the API incur substantial costs since the spread is up to 50% higher than when posting a trade via the API.

Any help or suggestions will be very much appreciated.

Thanks,
Max

**Comment by femtotrader** [comment]
Sorry this is out of the scope of this project.
What you are looking for is more an open source Metatrader server... but it doesn't exists for now (at least to my knowledge)
